language: ruby
os:
  - linux
  - osx
rvm:
  - "1.9.3"
  - "2.0.0"
  - "2.1" # latest 2.1.x
  - "2.2" # latest 2.2.x
  - "jruby-19mode"
  - "jruby-head"
script:
  bundle exec rake test
branches:
  except:
    - "readme-edits"
